wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.0
    start_time: 1639507534
    t:
      3:
      - 2
      4: 3.10.0
      5: 0.12.7
      8:
      - 5
